test fail check 2

diff --git a/.github/workflows/ami-format-check.yml b/.github/workflows/ami-format-check.yml
--- a/.github/workflows/ami-format-check.yml
+++ b/.github/workflows/ami-format-check.yml
@@ -23,9 +23,13 @@ jobs:
 
       - name: Packer Format
         run: |
-          if ! find deployment/ami -name '*.hcl' -exec packer fmt -check . \;; then
+          pwd
+          if ! find deployment/ami -name '*.hcl' -exec packer fmt -check .; then
             echo "Packer formatting check failed. Run 'packer fmt' to fix the formatting issues."
             exit 1
+          else
+            $?
+            echo "command failed"
           fi
         shell: bash
 
