test format error 2

diff --git a/.github/workflows/ami-format-check.yml b/.github/workflows/ami-format-check.yml
--- a/.github/workflows/ami-format-check.yml
+++ b/.github/workflows/ami-format-check.yml
@@ -23,7 +23,10 @@ jobs:
 
       - name: Packer Format
         run: |
-          find . -name './deployment/ami/*.hcl' -exec packer fmt -check . \;
+          if find . -name './deployment/ami/*.hcl' -exec packer fmt --check . \; | grep -q "WARN"; then
+            echo "Packer formatting check failed. Run 'packer fmt' to fix the formatting issues."
+            exit 1
+          fi
         shell: bash
 
       - name: Packer Validate
