workflow to update lt and asg

diff --git a/.github/workflows/biuld-ami.yml b/.github/workflows/biuld-ami.yml
--- a/.github/workflows/biuld-ami.yml
+++ b/.github/workflows/biuld-ami.yml
@@ -64,14 +64,6 @@ jobs:
         if: success()
         run: zip -r webapp.zip .
 
-      # - name: Install Packer
-      #   if: success()
-      #   run: |
-      #     wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
-      #     unzip packer_1.7.4_linux_amd64.zip
-      #     sudo mv packer /usr/local/bin/
-      #   shell: bash
-
       - name: Setting up packer
         uses: hashicorp/setup-packer@main
 
@@ -92,3 +84,118 @@ jobs:
             -var "ebsVolumeSize=${{ vars.EBS_VOLUME_SIZE }}" \
             -var "ebsVolumeType=${{ vars.EBS_VOLUME_TYPE }}" \
             -var "webappDestinationFolder=${{ vars.WEBAPP_DESTINATION_PATH }}" .
+
+  update-launch-template:
+    needs: build-ami
+    runs-on: ubuntu-latest
+    env:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_DEV }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_DEV }}
+      AWS_DEFAULT_REGION: 'us-east-1'
+
+    steps:
+    - name: Get Latest AMI ID
+      run: |
+        latest_ami=$(aws ec2 describe-images \
+          --owners self \
+          --query 'Images | sort_by(@, &CreationDate) | [-1].ImageId' --output text)
+        echo "Latest AMI ID: $latest_ami"
+        echo "::set-output name=ami_id::$latest_ami"
+      id: ami
+      
+    - name: Retrieve Existing Launch Template Configuration
+      run: |
+        launch_template_name="${{ vars.WEBAPP_PROJECT_NAME }}-${{ WEBAPP_ACCOUNT }}-lt"
+        aws ec2 describe-launch-template-versions \
+          --launch-template-name $launch_template_name \
+          --output json \
+          --query "LaunchTemplateVersions[0].LaunchTemplateData" \
+          > launch_template_data.json
+      shell: bash
+        
+    - name: Print Retrieved Launch Template JSON
+      run: cat launch_template_data.json
+
+    - name: Install jq
+      run: sudo apt-get install jq
+
+    - name: Replace AMI ID in Launch Template JSON
+      run: |
+        jq --arg ami_id "${{ steps.ami.outputs.ami_id }}" \
+          '.ImageId |= $ami_id' launch_template_data.json > updated_launch_template.json
+
+    - name: Print Updated Launch Template JSON
+      run: cat updated_launch_template.json
+
+    - name: Create Launch Template Version
+      run: |
+        aws ec2 create-launch-template-version \
+          --launch-template-name $launch_template_name \
+          --launch-template-data file://updated_launch_template.json
+      shell: bash
+        
+    - name: Query Launch Template Versions
+      run: |
+        versions=$(aws ec2 describe-launch-template-versions \
+          --launch-template-name $launch_template_name \
+          --output json \
+          --query "LaunchTemplateVersions[].VersionNumber")
+        latest_version=$(echo $versions | jq -r '.[0]')
+        echo "Latest Launch Template Version: $latest_version"
+        echo "::set-output name=latest_version::$latest_version"
+      id: template
+
+    - name: Set Latest Launch Template Version as Default
+      run: |
+        aws ec2 modify-launch-template \
+          --launch-template-name $launch_template_name \
+          --default-version ${{ steps.template.outputs.latest_version }} \
+          --output json
+        
+ refresh-autoscaling-group:
+    runs-on: ubuntu-latest
+    env:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_DEV }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_DEV }}
+      AWS_DEFAULT_REGION: 'us-east-1'
+
+    steps:
+    - name: Start Auto Scaling Group Instance Refresh
+      run: |
+        asg_name="${{ vars.WEBAPP_PROJECT_NAME }}-${{ WEBAPP_ACCOUNT }}-asg"
+        instance_refresh_command_output=$(aws autoscaling start-instance-refresh \
+          --auto-scaling-group-name $asg_name \
+          --preferences MinHealthyPercentage=100 \
+          --output json)
+        instance_refresh_id=$(echo $instance_refresh_command_output | jq -r '.InstanceRefreshId')
+        echo "Instance Refresh ID: $instance_refresh_id"
+        echo "::set-output name=instance_refresh_id::$instance_refresh_id"
+      shell: bash
+      id: instance_refresh
+        
+    - name: Wait for Instance Refresh to Complete
+      run: |
+        instance_refresh_id="${{ steps.instance_refresh.outputs.instance_refresh_id }}"
+        asg_name=${{ vars.WEBAPP_PROJECT_NAME }}-${{ WEBAPP_ACCOUNT }}-asg"
+        
+        # Check the status of the instance refresh in a loop
+        while true; do
+          instance_refresh_status=$(aws autoscaling describe-instance-refreshes \
+            --auto-scaling-group-name $asg_name \
+            --instance-refresh-ids $instance_refresh_id \
+            --query 'InstanceRefreshes[0].Status' \
+            --output json)
+          
+          echo "Instance Refresh Status: $instance_refresh_status"
+          
+          if [ "$instance_refresh_status" == '"Successful"' ]; then
+            echo "Instance Refresh completed successfully."
+            break
+          elif [ "$instance_refresh_status" == '"Cancelled"' ] || [ "$instance_refresh_status" == '"Failed"' ]; then
+            echo "Instance Refresh failed or was cancelled."
+            exit 1
+          else
+            echo "Waiting for Instance Refresh to complete..."
+            sleep 30  # Adjust the sleep interval as needed
+          fi
+        done
